const questions=[
{q:"Đặc điểm nào phản ánh đúng nhất bản sắc văn hóa Hà Nội?",a:["A. Chủ yếu được tạo nên bởi các di tích lịch sử.","B. Chưa hoàn toàn được tạo nên từ truyền thống, vì văn hóa Hà Nội còn chịu ảnh hưởng mạnh từ quá trình đô thị hóa.","C. Được hình thành từ sự kết hợp giữa truyền thống lâu đời, đời sống đô thị và quá trình giao lưu, tiếp biến văn hóa.","D. Chưa hoàn toàn chịu ảnh hưởng từ các vùng miền khác vì Hà Nội có bản sắc văn hóa riêng."],c:2},
{q:"Trong quan niệm truyền thống, hình ảnh “người Tràng An thanh lịch” thường được hiểu như thế nào?",a:["A. Gắn chủ yếu với sự giàu có, học thức và địa vị xã hội.","B. Chưa hoàn toàn chỉ thể hiện ở cách ăn mặc, mà còn ở cách ứng xử, lời ăn tiếng nói và sự tinh tế trong đời sống.","C. Chủ yếu thể hiện qua việc giữ nguyên các phong tục cổ truyền.","D. Chưa hoàn toàn khác biệt với sự thanh lịch nói chung, vì đây chỉ là một cách gọi mang tính địa phương."],c:1},
{q:"Vì sao ẩm thực có thể được xem là một biểu hiện của văn hóa Hà Nội?",a:["A. Vì Hà Nội có nhiều món ăn nổi tiếng và được khách du lịch yêu thích.","B. Chưa hoàn toàn vì mọi món ăn nổi tiếng ở Hà Nội đều có nguồn gốc từ chính Hà Nội.","C. Vì ẩm thực phản ánh khẩu vị, kỹ thuật chế biến, cách thưởng thức, lối sống và ký ức của cộng đồng.","D. Chưa hoàn toàn vì giá trị văn hóa của món ăn phụ thuộc chủ yếu vào mức độ nổi tiếng của nó."],c:2},
{q:"Nếu một làng nghề vẫn tạo ra sản phẩm truyền thống nhưng không còn truyền nghề cho thế hệ trẻ, nhận định nào phù hợp nhất?",a:["A. Làng nghề chưa hoàn toàn mất giá trị vì sản phẩm truyền thống vẫn còn tồn tại.","B. Giá trị văn hóa vẫn được bảo tồn đầy đủ nếu sản phẩm vẫn giữ được hình thức cũ.","C. Chưa hoàn toàn mất đi giá trị, nhưng tri thức, kỹ năng và kinh nghiệm nghề được truyền qua các thế hệ có nguy cơ mai một.","D. Làng nghề không còn giá trị văn hóa vì không còn người trẻ tham gia."],c:2},
{q:"Giá trị văn hóa của phố cổ Hà Nội được tạo nên như thế nào?",a:["A. Chủ yếu từ những ngôi nhà cổ và kiến trúc lâu đời.","B. Chưa hoàn toàn nằm ở kiến trúc, mà còn ở hoạt động buôn bán, phố nghề, ẩm thực và đời sống cộng đồng.","C. Chủ yếu nhờ khả năng thu hút khách du lịch và phát triển kinh tế.","D. Chưa hoàn toàn do các phố cổ đều duy trì nguyên vẹn cách sinh hoạt truyền thống."],c:1},
{q:"Khi Hà Nội tiếp nhận một yếu tố văn hóa từ bên ngoài, sau đó biến đổi và kết hợp với văn hóa bản địa để tạo ra nét riêng, hiện tượng này được hiểu phù hợp nhất là:",a:["A. Đồng hóa văn hóa.","B. Chưa hoàn toàn là giao lưu văn hóa.","C. Tiếp biến văn hóa.","D. Bảo tồn văn hóa."],c:2},
{q:"Tại sao lễ hội truyền thống ở Hà Nội có thể được xem là một không gian văn hóa?",a:["A. Vì lễ hội thường được tổ chức tại các di tích lịch sử và thu hút nhiều người tham gia.","B. Chưa hoàn toàn vì lễ hội không chỉ nhằm tưởng nhớ nhân vật hay sự kiện trong quá khứ.","C. Vì lễ hội kết hợp tín ngưỡng, nghi lễ, truyền thuyết, nghệ thuật, phong tục và sự tham gia của cộng đồng.","D. Chưa hoàn toàn vì giá trị của lễ hội ngày nay còn phụ thuộc vào khả năng thu hút khách du lịch."],c:2},
{q:"Muốn giữ gìn văn hóa Hà Nội thì phải giữ nguyên mọi thứ như trong quá khứ. Nhận định nào thuyết phục nhất?",a:["A. Đúng, vì thay đổi văn hóa chưa hoàn toàn đồng nghĩa với việc làm mất bản sắc.","B. Chưa hoàn toàn đúng, vì văn hóa Hà Nội có thể tiếp nhận những yếu tố mới, nhưng những giá trị truyền thống cần được giữ nguyên không thay đổi.","C. Chưa hoàn toàn đúng, vì bảo tồn văn hóa không nhất thiết là giữ nguyên mọi hình thức của quá khứ; quan trọng là giữ những giá trị cốt lõi, đồng thời cho phép văn hóa thích nghi và phát triển trong đời sống hiện đại.","D. Chưa hoàn toàn đúng, vì văn hóa luôn thay đổi theo thời gian."],c:2}
];
let qi=0,quizScore=0;
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active")}
function loadQuestion(){const q=questions[qi];document.getElementById("questionBox").innerHTML=`<div class="question"><h2>Câu ${qi+1}/${questions.length}</h2><p>${q.q}</p>${q.a.map((x,i)=>`<button class="answer" onclick="answerQuestion(${i})">${x}</button>`).join("")}</div>`}
function answerQuestion(i){if(i===questions[qi].c){quizScore++;alert("✅ Chính xác!")}else alert("❌ Chưa đúng!");qi++;if(qi<questions.length)loadQuestion();else{document.getElementById("questionBox").innerHTML=`<div class="random-result"><h2>🏆 KẾT QUẢ</h2><h1>${quizScore}/${questions.length}</h1><button class="big-button" onclick="restartQuiz()">Chơi lại</button></div>`}}
function restartQuiz(){qi=0;quizScore=0;document.getElementById("quizResult").innerHTML="";loadQuestion()}

const teams={1:Array.from({length:9},(_,i)=>`Người ${i+1} Tổ 1`),2:Array.from({length:9},(_,i)=>`Người ${i+1} Tổ 2`),3:Array.from({length:9},(_,i)=>`Người ${i+1} Tổ 3`),4:Array.from({length:9},(_,i)=>`Người ${i+1} Tổ 4`)};
let history=JSON.parse(localStorage.getItem("history")||"[]");
let selected=JSON.parse(localStorage.getItem("selected")||"[]");
let scores=JSON.parse(localStorage.getItem("scores")||'{"1":0,"2":0,"3":0,"4":0}');
function save(){localStorage.setItem("history",JSON.stringify(history));localStorage.setItem("selected",JSON.stringify(selected));localStorage.setItem("scores",JSON.stringify(scores))}
function randomPerson(){let need=[1,2,3,4].filter(t=>history.filter(x=>x.team===t).length<2);let pool=need.length?need:[1,2,3,4];let team=pool[Math.floor(Math.random()*pool.length)];let people=teams[team].filter(p=>!selected.includes(p));if(!people.length){alert("Tổ này đã hết người chưa được gọi.");return}let person=people[Math.floor(Math.random()*people.length)];selected.push(person);history.push({team,person});save();document.getElementById("randomResult").innerHTML=`<div class="random-result">🎉<br><strong>${person}</strong><br>Tổ ${team}</div>`;updateTeamStatus();updateHistory()}
function updateTeamStatus(){document.getElementById("teamStatus").innerHTML=[1,2,3,4].map(t=>{let n=history.filter(x=>x.team===t).length;return `<div class="team-card"><h3>Tổ ${t}</h3><div>${n}/9 người đã được gọi ${n>=2?"✅ Đủ tối thiểu":"⚠️ Chưa đủ 2 người"}</div></div>`}).join("")}
function updateHistory(){document.getElementById("history").innerHTML=history.length?history.map((x,i)=>`<p>Lượt ${i+1}: <strong>${x.person}</strong> – Tổ ${x.team}</p>`).join(""):"<p>Chưa có lượt nào.</p>"}

let rotation=0;
function spinWheel(){const prizeIndex=Math.floor(Math.random()*8);const team=(prizeIndex%4)+1;const points=prizeIndex<4?5:10;rotation+=1800+(360-prizeIndex*45-22.5);document.getElementById("wheel").style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{scores[team]+=points;save();document.getElementById("wheelResult").textContent=`🎉 TỔ ${team} +${points} ĐIỂM!`;updateScore()},5000)}
function updateScore(){document.getElementById("scoreBoard").innerHTML=[1,2,3,4].map(t=>`<div class="score-card"><h2>🏆 Tổ ${t}</h2><h2>${scores[t]} điểm</h2></div>`).join("")}

loadQuestion();updateTeamStatus();updateHistory();updateScore();
